# -*- coding: utf-8 -*-
"""shivaram gen ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4jkdy1ookiy0t0F-MdrTR-5ZAMR8WtX
"""

!pip install gtts

from gtts import gTTS
import IPython.display as display

text = input("Enter the text you want to convert to audio:\n")

tts = gTTS(text)
tts.save("output_audio.mp3")
print("✅ Audio generated successfully!")

display.Audio("output_audio.mp3", autoplay=True)